name: Setup Rust
description: Sets up Rust toolchain and caches

runs:
  using: "composite"
  steps:
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install Rust Tools
      shell: bash
      run: rustup component add rustfmt

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
        restore-keys: |
          ${{ runner.os }}-cargo-registry

    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ runner.os }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-ubuntu-latest
          ${{ runner.os }}-cargo-build-windows-latest
