name: Vocabulaire CI/CD

on:
  push:
    branches:
      - "**" # This will trigger the workflow on any branch that receives a git push
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # re-add windows-latest later

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup_rust

      - name: Build
        run: cargo build --release

      - name: Upload Linux binary
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: vocabulaire_linux
          path: target/release/vocabulaire

      - name: Upload Windows binary
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: vocabulaire_windows
          path: target\release\vocabulaire.exe

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup_rust

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Setup test DB
        run: |
          docker compose -f docker/docker-compose.yml up -d --build --remove-orphans

      - name: Run tests
        run: cargo test

      - name: Tear down test DB
        if: always()
        run: |
          docker compose -f docker/docker-compose.yml down
